Kola/dand 9 fix firebase build
segment-integrations/analytics-android-integration-firebase pull request #24
Opened 2019-11-15 14:15 UTC by breel93

**What does this PR do?**
 Bumps the Firebase dependency version from 17.2.0 to 17.2.1

**Are there breaking changes in this PR?**
Compiled Successfully and All test passed

**What are the relevant tickets?**
 Jira ticket : [#DAND-9](https://segmentcontractors.atlassian.net/jira/software/projects/DAND/boards/1?selectedIssue=DAND-9)

**Link to CC ticket**

2019-11-15 17:02 UTC, brennan commented on gradle.properties
> +VERSION=1.4.1-SNAPSHOT
Can we make this `2.0.0-SNAPSHOT`? Thanks!

2019-11-15 17:03 UTC, brennan requested changes
Just one comment. Thanks!

2019-11-19 23:47 UTC, brennan approved these changes

2021-09-08 20:31 UTC, prayansh commented
closing due to inactivity

2021-09-08 20:31 UTC, closed without merging